name: CI
on:
  push:
    branches:
      - main
  pull_request:
  

env:
  FOUNDRY_PROFILE: ci
  ETH_RPC_URL:  ${{ secrets.RPC_URL }}

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run tests
        run: |
          forge test --match-contract HodlChallenge --fork-url $ETH_RPC_URL --fork-block-number 14850000
